name: Pl3xMap-Marker
version: '4.0'
main: god.sentix.pl3xmarker.Main
api-version: 1.18
depend: [ squaremap ]
authors: [ Sentix ]
description: Simple marker extension for Pl3xMap/squaremap
website: https://github.com/SentixDev/Pl3xMap-Marker

commands:
  pl3xmarker:
    permission: pl3xmarker.marker

permissions:
  pl3xmarker.marker:
    description: Gives access to /pl3xmarker command
    default: op
